

//SignUp Temp Variables for creating shop
export const STORE_SHOP_NAME = "STORE_SHOP_NAME";
export const STORE_SHOP_DESC = "STORE_SHOP_DESC";
export const STORE_RELATED_CATEGORY = "STORE_RELATED_CATEGORY";
export const STORE_RELATED_CATEGORY_ID = "STORE_RELATED_CATEGORY_ID";
export const TOGGLE_CATEGORY_CHECK = "TOGGLE_CATEGORY_CHECK";
export const STORE_SHOP_CONTACT = "STORE_SHOP_CONTACT";
export const STORE_SHOP_LOCATION = "STORE_SHOP_LOCATION";
export const STORE_SHOP_DELIVERY_LOCATION = "STORE_SHOP_DELIVERY_LOCATION";
export const STORE_SHOP_IMAGE = "STORE_SHOP_IMAGE";
export const GET_SHOP_LOCATIONS = "GET_SHOP_LOCATIONS";

//SignUp Temp Variables for creating a product
export const STORE_PRODUCT_FIRST_IMAGE = "STORE_PRODUCT_FIRST_IMAGE";
export const STORE_PRODUCT_IMAGES = "STORE_PRODUCT_IMAGES";
export const STORE_SELECTED_SHOP_INFO = "STORE_SELECTED_SHOP_INFO";
export const STORE_SELECTED_CATEGORY_INFO = "STORE_SELECTED_CATEGORY_INFO";
export const STORE_PRODUCT_INFO = "STORE_PRODUCT_INFO";


// RESET
export const RESET_PRODUCT_CREATE_TEMP = "RESET_PRODUCT_CREATE_TEMP";
export const RESET_SETTINGS_TEMP = "RESET_SETTINGS_TEMP";
export const RESET_SHOP_CREATE_TEMP = "RESET_SHOP_CREATE_TEMP";
export const RESET_LOCAL_SIGN_UP_TEMP = "RESET_LOCAL_SIGN_UP_TEMP";
export const CATEGORY_FILTER_TEMP = "CATEGORY_FILTER_TEMP";

// FILTER
export const RESET_SHOP_FILTERS = "RESET_SHOP_FILTERS";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const FILTERED_CATEGORY_ID = "FILTERED_CATEGORY_ID";

// SETTINGS
export const STORE_SELECTED_ISLAND = "STORE_SELECTED_ISLAND";

//SHOPPING CART
export const POPULATE_CART = "POPULATE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_CART_QTY = "INCREMENT_CART_QTY";
export const DECREMENT_CART_QTY = "DECREMENT_CART_QTY";
export const RESET_SHOPPING_CART = "RESET_SHOPPING_CART";