export const CREATE_USER_IMAGE = 'CREATE_USER_IMAGE';
export const CREATE_USER_AVATAR = 'CREATE_USER_AVATAR';

export const CREATE_SHOP_IMAGE = 'CREATE_SHOP_IMAGE';
export const CREATE_SHOP_AVATAR = 'CREATE_SHOP_AVATAR';

export const CREATE_PRODUCT_IMAGES = 'CREATE_PRODUCT_IMAGES';
//this is for creating default image and avatar for the first image 
//in the array.
export const CREATE_PRODUCT_DEFAULT_IMAGE = 'CREATE_PRODUCT_DEFAULT_IMAGE';
export const CREATE_PRODUCT_DEFAULT_AVATAR = 'CREATE_PRODUCT_DEFAULT_AVATAR';
